# @package _global_
common_cfg:
  time_receptive_field: 1
  n_future_frames: 8
  pretrained_path: '/mnt/nas20/wenxin.shao/misc/ckpt/fiery.ckpt'
  dataset:
    dataroot: './nuscenes/'
    version: 'trainval'
    name: 'nuscenes'
    ignore_index: 255  # ignore index when creating flow/offset labels
    filter_invisible_vehicles: true  # Filter vehicles that are not visible from the cameras
  image:
    names: ['CAM_FRONT_LEFT', 'CAM_FRONT', 'CAM_FRONT_RIGHT', 'CAM_BACK_LEFT', 'CAM_BACK', 'CAM_BACK_RIGHT']
    original_height: 900
    original_width: 1600
    resize_scale: 0.3
    top_crop: 46
    final_dim: [224, 480]
  lift:
    x_bound: [-50.0, 50.0, 0.5]
    y_bound: [-50.0, 50.0, 0.5]
    z_bound: [-10.0, 10.0, 20.0]
    d_bound: [2.0, 50.0, 1.0]
  model:
    encoder:
      downsample: 8
      name: 'efficientnet-b4'
      out_channels: 64
      use_depth_distribution: true
    temporal_model:
      name: 'identity'
      start_out_channels: 64
      extra_in_channels: 0
      inbetween_layers: 0
      pyramid_pooling: false
      input_egopose: false
    decoder:
      use_feature_buffer: true
      use_command_buffer: true
    bn_momentum: 0.1
